In [2]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range("20130101", periods=15)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15'],
              dtype='datetime64[ns]', freq='D')

In [5]:
import pandas as pd
import numpy as np

dates = pd.date_range("2024-01-01", periods=15)

df = pd.DataFrame(
    np.random.randn(15, 4),
    index=dates,
    columns=list("ABCD")
)

df

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-09 -0.229832  1.364809 -0.617946 -0.403749
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [6]:
# Dictionary 
dict={'Shoaib':5.5,'Ali':6.5,'Ahmed':7.5}
dict

{'Shoaib': 5.5, 'Ali': 6.5, 'Ahmed': 7.5}

In [7]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [8]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[s]
 2   C       4 non-null      float32
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      object
dtypes: category(1), datetime64[s](1), float32(1), float64(1), int32(1), object(1)
memory usage: 288.0+ bytes

In [10]:
df.tail()

                   A         B         C         D
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [11]:
df.index

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12',
               '2024-01-13', '2024-01-14', '2024-01-15'],
              dtype='datetime64[ns]', freq='D')

In [12]:
df2.index

Index([0, 1, 2, 3], dtype='int64')

In [13]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [14]:
df.to_numpy()

array([[ 1.29815193,  0.40615647,  0.92045178, -1.24071297],
       [ 2.09604889, -0.52766919,  2.07221834,  0.58005718],
       [-1.4472443 , -1.28550084, -0.11669449,  0.91583172],
       [ 1.14298702,  0.70061962,  1.31546744,  0.63289006],
       [ 0.41098248, -0.81311965,  0.17606171, -0.35804391],
       [ 0.49048783,  0.50399356,  1.5020282 ,  0.85393512],
       [ 0.93435215, -0.71836574, -1.29220903,  0.46334533],
       [ 1.08372265, -0.0212239 , -0.897046  , -0.65503281],
       [-0.22983165,  1.3648086 , -0.6179457 , -0.40374864],
       [ 0.54888449, -1.49527469,  0.43793869,  0.03441294],
       [ 0.29961753, -1.27745093,  3.46331596, -1.18143513],
       [ 1.30964309, -0.87445626, -1.76787333, -0.103695  ],
       [-0.21124761, -0.16179988,  0.08656773, -1.23047868],
       [ 0.3633573 ,  0.15236854,  0.35543498, -1.05605151],
       [ 0.59314507,  2.37171967, -0.59533563,  1.35116245]])

In [15]:
df.describe()

               A          B          C          D
count  15.000000  15.000000  15.000000  15.000000
mean    0.578870  -0.111680   0.336159  -0.093171
std     0.827977   1.069076   1.366271   0.866511
min    -1.447244  -1.495275  -1.767873  -1.240713
25%     0.331487  -0.843788  -0.606641  -0.855542
50%     0.548884  -0.161800   0.176062  -0.103695
75%     1.113355   0.455075   1.117960   0.606474
max     2.096049   2.371720   3.463316   1.351162

In [16]:
df

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-09 -0.229832  1.364809 -0.617946 -0.403749
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [17]:
df.T

,2024-01-01,2024-01-02,2024-01-03,2024-01-04,2024-01-05,2024-01-06,2024-01-07,2024-01-08,2024-01-09,2024-01-10,2024-01-11,2024-01-12,2024-01-13,2024-01-14,2024-01-15
A,1.298152,2.096049,-1.447244,1.142987,0.410982,0.490488,0.934352,1.083723,-0.229832,0.548884,0.299618,1.309643,-0.211248,0.363357,0.593145
B,0.406156,-0.527669,-1.285501,0.700620,-0.813120,0.503994,-0.718366,-0.021224,1.364809,-1.495275,-1.277451,-0.874456,-0.161800,0.152369,2.371720
C,0.920452,2.072218,-0.116694,1.315467,0.176062,1.502028,-1.292209,-0.897046,-0.617946,0.437939,3.463316,-1.767873,0.086568,0.355435,-0.595336
D,-1.240713,0.580057,0.915832,0.632890,-0.358044,0.853935,0.463345,-0.655033,-0.403749,0.034413,-1.181435,-0.103695,-1.230479,-1.056052,1.351162

In [18]:
df.sort_index(axis=1, ascending=False)
# here 1 means columns
# axis=0 means rows
# axis=1 means columns

                   D         C         B         A
2024-01-01 -1.240713  0.920452  0.406156  1.298152
2024-01-02  0.580057  2.072218 -0.527669  2.096049
2024-01-03  0.915832 -0.116694 -1.285501 -1.447244
2024-01-04  0.632890  1.315467  0.700620  1.142987
2024-01-05 -0.358044  0.176062 -0.813120  0.410982
2024-01-06  0.853935  1.502028  0.503994  0.490488
2024-01-07  0.463345 -1.292209 -0.718366  0.934352
2024-01-08 -0.655033 -0.897046 -0.021224  1.083723
2024-01-09 -0.403749 -0.617946  1.364809 -0.229832
2024-01-10  0.034413  0.437939 -1.495275  0.548884
2024-01-11 -1.181435  3.463316 -1.277451  0.299618
2024-01-12 -0.103695 -1.767873 -0.874456  1.309643
2024-01-13 -1.230479  0.086568 -0.161800 -0.211248
2024-01-14 -1.056052  0.355435  0.152369  0.363357
2024-01-15  1.351162 -0.595336  2.371720  0.593145

In [19]:
df.sort_values(by="B")

                   A         B         C         D
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-09 -0.229832  1.364809 -0.617946 -0.403749
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [20]:
df

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-09 -0.229832  1.364809 -0.617946 -0.403749
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [21]:
df['A']

2024-01-01    1.298152
2024-01-02    2.096049
2024-01-03   -1.447244
2024-01-04    1.142987
2024-01-05    0.410982
2024-01-06    0.490488
2024-01-07    0.934352
2024-01-08    1.083723
2024-01-09   -0.229832
2024-01-10    0.548884
2024-01-11    0.299618
2024-01-12    1.309643
2024-01-13   -0.211248
2024-01-14    0.363357
2024-01-15    0.593145
Freq: D, Name: A, dtype: float64

In [22]:
df[['A', 'B']]

                   A         B
2024-01-01  1.298152  0.406156
2024-01-02  2.096049 -0.527669
2024-01-03 -1.447244 -1.285501
2024-01-04  1.142987  0.700620
2024-01-05  0.410982 -0.813120
2024-01-06  0.490488  0.503994
2024-01-07  0.934352 -0.718366
2024-01-08  1.083723 -0.021224
2024-01-09 -0.229832  1.364809
2024-01-10  0.548884 -1.495275
2024-01-11  0.299618 -1.277451
2024-01-12  1.309643 -0.874456
2024-01-13 -0.211248 -0.161800
2024-01-14  0.363357  0.152369
2024-01-15  0.593145  2.371720

In [23]:
df[0:3]

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832

In [24]:
df.shape

(15, 4)

In [ ]:
df.iloc[0:3, 0:2]  # index ko lock karney k liye iloc use hota hai

                   A         B
2024-01-01  1.298152  0.406156
2024-01-02  2.096049 -0.527669
2024-01-03 -1.447244 -1.285501

In [26]:
df.loc[:, ['A', 'B']]

                   A         B
2024-01-01  1.298152  0.406156
2024-01-02  2.096049 -0.527669
2024-01-03 -1.447244 -1.285501
2024-01-04  1.142987  0.700620
2024-01-05  0.410982 -0.813120
2024-01-06  0.490488  0.503994
2024-01-07  0.934352 -0.718366
2024-01-08  1.083723 -0.021224
2024-01-09 -0.229832  1.364809
2024-01-10  0.548884 -1.495275
2024-01-11  0.299618 -1.277451
2024-01-12  1.309643 -0.874456
2024-01-13 -0.211248 -0.161800
2024-01-14  0.363357  0.152369
2024-01-15  0.593145  2.371720

In [28]:
df

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-03 -1.447244 -1.285501 -0.116694  0.915832
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-09 -0.229832  1.364809 -0.617946 -0.403749
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-13 -0.211248 -0.161800  0.086568 -1.230479
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [29]:
df.iloc[3]

A    1.142987
B    0.700620
C    1.315467
D    0.632890
Name: 2024-01-04 00:00:00, dtype: float64

In [30]:
df.iloc[3:5, 0:2]

                   A        B
2024-01-04  1.142987  0.70062
2024-01-05  0.410982 -0.81312

In [31]:
import seaborn as sns
kashti = sns.load_dataset('titanic')
kashti

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [32]:
kashti.sample(100)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
64,0,1,male,NaN,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
155,0,1,male,51.0,0,1,61.3792,C,First,man,True,NaN,Cherbourg,no,False
735,0,3,male,28.5,0,0,16.1000,S,Third,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653,1,3,female,NaN,0,0,7.8292,Q,Third,woman,False,NaN,Queenstown,yes,True
655,0,2,male,24.0,2,0,73.5000,S,Second,man,True,NaN,Southampton,no,False
603,0,3,male,44.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
439,0,2,male,31.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
235,0,3,female,NaN,0,0,7.5500,S,Third,woman,False,NaN,Southampton,no,True

In [33]:
df[df["A"] > 0]

                   A         B         C         D
2024-01-01  1.298152  0.406156  0.920452 -1.240713
2024-01-02  2.096049 -0.527669  2.072218  0.580057
2024-01-04  1.142987  0.700620  1.315467  0.632890
2024-01-05  0.410982 -0.813120  0.176062 -0.358044
2024-01-06  0.490488  0.503994  1.502028  0.853935
2024-01-07  0.934352 -0.718366 -1.292209  0.463345
2024-01-08  1.083723 -0.021224 -0.897046 -0.655033
2024-01-10  0.548884 -1.495275  0.437939  0.034413
2024-01-11  0.299618 -1.277451  3.463316 -1.181435
2024-01-12  1.309643 -0.874456 -1.767873 -0.103695
2024-01-14  0.363357  0.152369  0.355435 -1.056052
2024-01-15  0.593145  2.371720 -0.595336  1.351162

In [38]:
kashti[kashti["fare"] < 5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
179,0,3,male,36.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
263,0,1,male,40.0,0,0,0.0000,S,First,man,True,B,Southampton,no,True
271,1,3,male,25.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,yes,True
277,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
378,0,3,male,20.0,0,0,4.0125,C,Third,man,True,NaN,Cherbourg,no,True
413,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
466,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
633,0,1,male,NaN,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True